// === Equipe TEA Encantar ===
// Cada profissional é uma entrada. Para adicionar, copie um bloco e preencha.
// (No futuro, isso pode vir direto do banco de dados.)
window.EQUIPE = [
  {
    nome: "Raquel Moreira Gonçalves",
    cargo: "Psicóloga",
    registro: "CRP 05/65717",
    experiencia: "6 anos",
    publico: ["Infantil", "Adulto", "Idoso"],
    foto: "assets/fotos/equipe/raquel.jpg",
    bio: "Psicóloga clínica com atuação voltada para crianças, adolescentes e adultos. Realizo atendimentos com foco no acolhimento, na escuta qualificada e na promoção da saúde mental, oferecendo um espaço seguro, ético e humanizado para cada paciente.",
    mensagem: "Troca de experiências e a construção de um cuidado mais humanizado e acolhedor para cada paciente.",
    formacao: [
      "Graduação em Psicologia",
      "Pós-graduação em Saúde Mental, Psicopatologia e Atenção Psicossocial",
      "Pós-graduação em Psicologia Hospitalar",
      "Pós-graduação em Terapia Cognitivo-Comportamental (TCC)",
      "Pós-graduação em Transtorno do Espectro Autista (TEA)",
      "Pós-graduação em Neuropsicologia e Reabilitação",
    ],
  },
  {
    nome: "Tainá Manhães",
    cargo: "Psicóloga",
    registro: "CRP 05/71180",
    experiencia: "2 anos",
    publico: ["Infantil", "Adulto"],
    foto: "assets/fotos/equipe/taina.jpg",
    bio: "Psicóloga especialista em Saúde Mental. Meu propósito é oferecer um cuidado humano e acolhedor. No atendimento infantil ao TEA, uso o brincar terapêutico para conectar e desenvolver as potências de cada criança, com colo e orientação prática para acolher também o coração dos pais.",
    mensagem: "Fazer parte da equipe significa ajudar a alcançar as pessoas que precisam de cuidado. É gratificante transformar a técnica da psicologia em afeto e conexão humana!",
    formacao: [
      "Graduação em Psicologia (Universidade Estácio de Sá)",
      "Pós-graduação em Saúde Mental e Atenção Psicossocial (Universidade Estácio de Sá)",
    ],
  },
  {
    nome: "Vanusa dos Santos Cordeiro",
    cargo: "Psicomotricista",
    registro: "CBO 223915",
    experiencia: "1 ano",
    publico: ["Infantil"],
    foto: "assets/fotos/equipe/vanusa.jpg",
    bio: "Psicomotricista dedicada ao desenvolvimento infantil, com um olhar acolhedor e lúdico para cada criança e sua família.",
    mensagem: "",
    formacao: [
      "Graduação em Psicomotricidade e Ludicidade na Educação Infantil",
      "Curso de ABA e Modelo Denver",
    ],
  },
  {
    nome: "Isabela Unis",
    cargo: "Psicóloga",
    registro: "CRP 05/84591",
    experiencia: "6 meses",
    publico: ["Adulto", "Idoso"],
    foto: "assets/fotos/equipe/isabela.jpg",
    bio: "Psicóloga clínica e pós-graduanda em Terapia de Aceitação e Compromisso, com atuação junto a adolescentes, adultos e idosos. Trabalho com escuta qualificada, acolhimento e intervenções personalizadas, com empatia e compromisso com o cuidado.",
    mensagem: "A troca entre diferentes visões sobre o mesmo caso, com um profissional ajudando o outro a acompanhar o paciente de forma integrada e completa.",
    formacao: [
      "Graduação em Psicologia (UNASP)",
      "Pós-graduação em Terapia de Aceitação e Compromisso, em andamento (UNIFATEC)",
      "Curso sobre luto",
      "Curso de ACT (Terapia de Aceitação e Compromisso)",
    ],
  },
  {
    nome: "Giovana Monteiro dos Santos",
    cargo: "Terapeuta Ocupacional",
    registro: "CREFITO/2 024687-TO",
    experiencia: "3 anos",
    publico: ["Infantil"],
    foto: "assets/fotos/equipe/giovana.jpg",
    bio: "Terapeuta Ocupacional com Certificação Internacional em Integração Sensorial de Ayres. Atuo na reabilitação infantil (0 a 12 anos).",
    mensagem: "A tranquilidade e a leveza de trabalhar num lugar bom.",
    formacao: [
      "Graduação em Terapia Ocupacional (UFRJ)",
      "Certificação Internacional em Integração Sensorial de Ayres (CLASI/CASI)",
      "Curso de Seletividade Alimentar: Terapia Ocupacional e Integração Sensorial (LUDENS)",
      "Capacitação em Tratamento de Seletividade Alimentar (Pratinho Feliz PRO)",
      "Terapeuta ABA (RB Psicologia)",
      "Método Therapy Taping, básico e avançado",
      "Confecção de Órteses para mão, punho e dedos (HANDS ON ÓRTESES)",
    ],
  },
  {
    nome: "Daise Matheus",
    cargo: "Musicoterapeuta",
    registro: "ABMT-RJ 570",
    experiencia: "2 anos",
    publico: ["Infantil"],
    foto: "assets/fotos/equipe/daise.jpg",
    bio: "Musicoterapeuta pós-graduada, utiliza a música como recurso terapêutico para promover desenvolvimento, bem-estar, comunicação, interação social e qualidade de vida, com um atendimento humanizado e centrado nas necessidades de cada pessoa.",
    mensagem: "Poder contribuir no desenvolvimento, promovendo aprendizado, acolhimento e crescimento mútuo.",
    formacao: [
      "Pós-graduação em Musicoterapia",
      "Educação Especial e Inclusiva",
      "ABA na prática",
      "Música e Neurociências: fundamentos para Musicoterapia",
      "Musicoterapia para musicoterapeutas",
      "Neurociência do Desenvolvimento",
      "Música e Saúde Integrativa",
      "Neurociência da Música",
    ],
  },
  {
    nome: "Maria de Fátima da Costa",
    cargo: "Fonoaudióloga",
    registro: "CRFa 1-16672",
    experiencia: "4 anos",
    publico: ["Infantil"],
    foto: "assets/fotos/equipe/maria-fatima.jpg",
    bio: "Mãe amorosa, professora e fonoaudióloga. Minha atuação é fundamentada no conhecimento científico, no compromisso ético e no afeto. Trabalho para desenvolver a comunicação e a linguagem, integrando a família como base do plano terapêutico, em parceria com a escola, visando o desenvolvimento integral do paciente.",
    mensagem: "Aqui na TEA Encantar acolhemos as famílias com comprometimento e afeto, ajudamos a dar voz e a reescrever histórias.",
    formacao: [
      "Graduação em Fonoaudiologia (UFRJ)",
      "Graduação em História (UFF)",
      "Pós-graduação em Métodos e Processos do Ensino Superior (AFE)",
    ],
  },
  {
    nome: "Juciara Duarte",
    cargo: "Psicomotricista",
    registro: "CBO 2239-15",
    experiencia: "1 ano e 6 meses",
    publico: ["Infantil"],
    foto: "assets/fotos/equipe/juciara.jpg",
    bio: "Psicomotricista voltada ao desenvolvimento infantil. Atendimento especializado para crianças e adolescentes, com foco no desenvolvimento motor, cognitivo e emocional, com olhar acolhedor e individualizado.",
    mensagem: "É uma alegria fazer parte desta equipe, contribuindo com um olhar acolhedor e humanizado para o desenvolvimento de crianças e adolescentes.",
    formacao: [
      "Psicomotricidade e Ludicidade na Educação Infantil",
      "Pós-graduação em ABA (Análise do Comportamento Aplicada ao Autismo)",
      "Pós-graduação em Psicomotricidade Institucional, Clínica e TGD/TEA",
      "Extensão em Psicomotricidade e Desenvolvimento Humano",
      "Extensão em Transtorno do Espectro Autista (TEA)",
      "Extensão em TDAH",
      "Extensão em Psicomotricidade Relacional",
      "Capacitação em Psicomotricidade e Aprendizagem",
      "Curso ABA no TEA (Aplicador ABA)",
      "Curso de Acompanhante Terapêutico",
    ],
  },
  {
    nome: "Adriano Queiroz",
    cargo: "Psicomotricista e Educador Físico",
    registro: "CREF 043607-G/RJ",
    experiencia: "7 anos",
    publico: ["Infantil"],
    foto: "assets/fotos/equipe/adriano.jpg",
    bio: "Profissional de Educação Física, especialista em Psicomotricidade. Dedica-se ao desenvolvimento integral dos alunos e pacientes por meio do movimento, explorando aspectos motores, cognitivos e emocionais de forma lúdica e significativa.",
    mensagem: "Acredito na força do trabalho coletivo, na troca de experiências e no crescimento profissional conjunto, sempre visando o melhor desenvolvimento dos pacientes.",
    formacao: [
      "Licenciatura em Educação Física (UFRJ)",
      "Formação em Psicomotricidade Sistêmica (Centro de Estudos da Criança - CEC)",
      "Curso de Análise do Desenvolvimento Humano (Fiocruz)",
      "Curso de Desenvolvimento Profissional em Educação Infantil (Fiocruz)",
      "Publicação no III Congresso de Estudos da Infância (UERJ, 2021)",
    ],
  },
  {
    nome: "Michele Gonçalves",
    cargo: "Psicomotricista",
    registro: "",
    experiencia: "2 anos",
    publico: ["Infantil", "Adulto", "Idoso"],
    foto: "assets/fotos/equipe/michele.jpg",
    bio: "Graduada em Psicomotricidade e graduanda em Nutrição e Terapia Ocupacional. Atuação voltada ao desenvolvimento infantil, unindo psicomotricidade, funcionalidade e nutrição para promover autonomia, aprendizado e qualidade de vida de forma acolhedora e individualizada.",
    mensagem: "O que mais me motiva é acompanhar o crescimento e as conquistas de cada criança, celebrando cada avanço e contribuindo para seu desenvolvimento de forma integral.",
    formacao: [
      "Graduação em Psicomotricidade (Centro Universitário Cidade Verde)",
      "Pós-graduação em ABA aplicada ao autismo",
      "VB-MAPP e alfabetização (ABA: autismo, TDAH e TOD)",
      "ABA no autismo",
      "Modelo Denver 1 e 2",
      "Cursos com Regina Bergamo",
      "Fisioterapia aquática",
      "Gerontologia",
      "Psicomotricidade Institucional, Clínica e TGD/TEA",
    ],
  },
  {
    nome: "Silvana Moreira",
    cargo: "Psicomotricista e Massoterapeuta",
    registro: "CBO 2239-15",
    experiencia: "9 meses",
    publico: ["Infantil"],
    foto: "assets/fotos/equipe/silvana.jpg",
    bio: "Profissional dedicada ao cuidado e ao desenvolvimento humano, atuando como psicomotricista e técnica em massoterapia. Tenho experiência em estimulação motora, cognitiva e emocional, além de técnicas terapêuticas voltadas ao bem-estar e ao atendimento humanizado.",
    mensagem: "O que mais gosto em fazer parte da equipe é poder contribuir para o desenvolvimento e o bem-estar das pessoas, trabalhando em conjunto e oferecendo um atendimento humanizado e de qualidade.",
    formacao: [
      "Graduação em Psicomotricidade (UNICV)",
      "Curso Técnico em Massoterapia (Escola Técnica Vencer)",
    ],
  },
];
